import "dotenv/config";
import pg from "pg";

const { Pool } = pg;

const descriptionsById = {
  "4e6f75d3-c196-4f36-8101-6e1d02774d5e":
    "Anello urbano scorrevole, ideale per chi vuole camminare in città senza rinunciare a varieta di ambienti. Il percorso collega zone molto diverse tra loro: strade di quartiere, tratti lungo l'acquedotto, passaggi tra street art e aree residenziali. L'impegno fisico e contenuto per distanza e dislivello, ma richiede attenzione agli attraversamenti stradali e al traffico locale nelle ore di punta. Terreno prevalentemente asfaltato o pavimentato, quindi adatto tutto l'anno con scarpe comode da cammino. Ottimo come uscita breve di allenamento, per orientarsi nei quartieri dell'est di Roma e mantenere un ritmo regolare senza difficolta tecniche.",
  "0de533eb-5a04-4afa-9003-be421c239e45":
    "Itinerario montano classico nei Lucretili, con salita progressiva da quota medio-alta fino alla dorsale del Pellecchia. La traccia alterna sterrata, sentiero nel bosco e tratti piu aperti in cresta, con dislivello importante ma ben distribuito. L'impegno e di livello medio: servono passo costante, autonomia d'acqua e buona gestione dei tempi, soprattutto nei mesi caldi. In cima il panorama ripaga ampiamente, con visuali ampie sull'Appennino centrale e sulle vallate laziali. Il fondo puo diventare scivoloso dopo pioggia, quindi meglio scarponi con buona aderenza. Percorso consigliato a escursionisti gia abituati a uscite da 4-5 ore.",
  "7d294c13-109d-4fe4-8def-9d9fa46f60dd":
    "Tappa lunga ma tecnicamente semplice, pensata per chi ama i cammini storici su strade bianche, tratturi e sentieri collinari. Il dislivello resta moderato rispetto alla distanza, quindi la vera difficolta e la continuita del passo per diverse ore. Lungo il tragitto si alternano borghi, campagna e tratti boschivi, con un andamento regolare senza passaggi esposti. Terreno misto: sterrato compatto, carrarecce e brevi segmenti asfaltati in ingresso/uscita dai centri abitati. Consigliati bastoncini e gestione attenta di acqua e alimentazione. Ideale per chi prepara traversate multi-giorno e vuole lavorare su resistenza e orientamento su tracce lunghe.",
  "a90e0e77-b83a-4394-8bc8-c9aef821086e":
    "Anello d'alta quota nei Simbruini con partenza comoda da Campo dell'Osso e salita graduale verso ambienti sempre piu panoramici. Il percorso attraversa faggete e ampi pendii erbosi, poi guadagna la dorsale sommitale con vista estesa sulle principali cime dell'Appennino centrale. L'impegno e medio: distanza gestibile ma dislivello presente, da affrontare con ritmo regolare. Fondo in prevalenza su sentiero battuto, con alcuni tratti sassosi in prossimita della cresta. In caso di vento o meteo incerto la percezione di fatica aumenta rapidamente. Escursione molto adatta in primavera e autunno, con scarponi da trekking e una minima abitudine ai percorsi montani sopra i 1500 metri.",
  "c87b5aa5-e26c-4770-b7a9-46743490d16a":
    "Percorso molto breve e poco dislivellato, adatto come camminata esplorativa o test rapido di orientamento/GPS. L'impegno fisico e basso, ma resta utile per prendere confidenza con gestione traccia, ritmo e soste. Terreno facile e continuo, senza passaggi tecnici, ideale anche per chi vuole fare uscita leggera vicino a quota bassa. Data la durata ridotta, puo essere combinato con altri anelli o usato come giro introduttivo prima di uscite piu lunghe. In estate conviene comunque evitare le ore piu calde e portare acqua minima. Buona opzione per mantenere la gamba attiva nei giorni in cui non hai tempo per escursioni estese.",
  "5d66d24a-bda3-4798-bf54-5494ee6c57b1":
    "Salita panoramica in ambiente d'alta montagna con partenza da Campo Imperatore e sviluppo su sentiero evidente verso il Monte Aquila. Non presenta difficolta alpinistiche, ma quota, vento e fondo ghiaioso richiedono attenzione e passo regolare. L'impegno e medio: distanza contenuta ma dislivello concentrato, con tratti finali piu sostenuti. In cambio offre uno dei migliori belvedere sul massiccio del Gran Sasso, con visuali ampie su Corno Grande e altopiano. Periodo consigliato da tarda primavera a inizio autunno, verificando sempre meteo e stabilita del terreno. Scarponi, strato antivento e idratazione adeguata sono essenziali anche nelle giornate apparentemente miti.",
  "cc206e4b-1b6f-4a55-a155-a62a0f12365f":
    "Anello molto vario che combina natura, acqua e archeologia in un'unica uscita lunga ma accessibile. Il tracciato attraversa la zona della Banditaccia e prosegue verso forre e salti d'acqua del territorio di Cerveteri, con continui cambi di scenario. L'impegno e medio per la distanza totale: il dislivello non e estremo, ma fondo umido, tratti fangosi e guadi possono rallentare. Terreno misto su sentiero, sterrato e passaggi vicino al corso d'acqua, dove conviene muoversi con prudenza. Consigliate scarpe impermeabili e bastoncini, soprattutto dopo pioggia. Percorso ideale per chi cerca un trekking culturale-naturalistico completo in giornata.",
  "23113f24-ba2b-4bc2-8cf4-329b29487616":
    "Escursione appenninica impegnativa sul gruppo dei Monti Aurunci, con sviluppo in quota e dislivello importante. La progressione richiede allenamento aerobico, gestione dei tempi e buona autonomia personale: non e una traccia da affrontare con leggerezza. Il terreno alterna sentieri montani, tratti pietrosi e sezioni piu ripide in salita, con panorami molto ampi sul litorale e sulle dorsali interne nelle giornate limpide. L'ambiente e aperto e ventilato, quindi meteo e temperature incidono molto sulla fatica percepita. Consigliati scarponi strutturati, bastoncini e partenza mattutina. Itinerario adatto a escursionisti esperti su uscite da oltre 5 ore di cammino effettivo.",
  "2cacb1f6-da35-4386-858e-ef45dcea5406":
    "Percorso di media lunghezza sul settore del Monte Gennaro con profilo altimetrico relativamente dolce e cammino continuo. L'impegno fisico resta moderato: la distanza si sente, ma l'escursione e gestibile per chi ha un minimo di abitudine ai trekking collinari/montani. Il fondo e in gran parte su sentiero e sterrato, con tratti nel bosco e aperture panoramiche che rendono il giro vario senza difficolta tecniche marcate. Ideale per allenare resistenza e ritmo, specialmente in mezza stagione quando il terreno e piu asciutto. In estate e consigliata partenza presto. Buona scelta per chi vuole una giornata piena ma senza passaggi esposti o estremamente ripidi.",
  "ab98c239-ae5b-4643-8247-2ff6275213f6":
    "Prima tappa della Via degli Dei con uscita graduale da Bologna verso i rilievi appenninici. E una giornata lunga ma tecnicamente lineare: la difficolta principale e la gestione della distanza e del dislivello progressivo, non la presenza di passaggi complessi. Il percorso alterna tratti urbani iniziali, carrarecce, sentieri di collina e strade bianche, con panorami via via piu aperti man mano che ci si allontana dalla citta. Ottima tappa di transizione per entrare nel ritmo del cammino, curando idratazione e regolarita del passo. Consigliati scarponcini leggeri e bastoncini. Buona anche per chi vuole provare un segmento rappresentativo della traversata verso Firenze.",
  "bcd47247-a577-4317-b850-d70e87409901":
    "Seconda tappa della Via degli Dei, piu esigente della precedente per sviluppo e dislivello in salita. Qui conta la tenuta fisica: salita lunga, ritmo da gestire e attenzione alle energie per arrivare lucidi alla fine. Il tracciato attraversa ambienti appenninici classici tra boschi, crinali e sterrati, con fondo variabile che puo diventare scivoloso in caso di pioggia. Non presenta difficolta tecniche alpinistiche, ma richiede passo allenato e buona organizzazione di acqua/cibo lungo la giornata. E una tappa chiave del cammino per capire il proprio livello di autonomia su percorrenze impegnative. Consigliata a escursionisti con allenamento medio-buono su uscite di lunga durata.",
  "a1670985-bb76-4ff2-800e-e496fe512c41":
    "Tappa appenninica di collegamento verso il Passo della Futa, con sviluppo piu contenuto ma dislivello ancora significativo. Il percorso resta escursionistico su sentieri e strade forestali, senza tratti tecnici complessi, ma con saliscendi che richiedono continuita di passo. Ambiente tipico di dorsale: bosco, crinali aperti e lunghi tratti in natura, con clima che puo cambiare rapidamente tra mattina e pomeriggio. Ideale per chi vuole una giornata intensa ma meno lunga rispetto alle tappe da oltre 25 km. La gestione delle pause e fondamentale per non perdere ritmo. Consigliati bastoncini e calzature con buona trazione, soprattutto se il terreno e umido.",
  "ffef4196-97fc-48a1-a4cf-ac53440bd497":
    "Tappa di discesa progressiva dall'area del Passo della Futa verso quote piu basse, con chilometraggio importante e forte componente di sviluppo lineare. Anche se il bilancio altimetrico favorisce la discesa, l'impegno resta medio-alto per durata e impatto muscolare su ginocchia e caviglie. Il tracciato passa tra boschi, sterrati e segmenti di collegamento ai centri abitati, mantenendo una buona varieta paesaggistica. Giornata ideale per curare tecnica di cammino in discesa e gestione dei carichi nello zaino. Non presenta passaggi tecnici particolari, ma richiede concentrazione costante sul fondo. Utile partire presto per arrivare con margine e godersi i tratti panoramici finali.",
  "bc6f6e5d-14be-48eb-b8cf-1c646bd793c1":
    "Tappa collinare della Via degli Dei con dislivello nuovamente in salita e sviluppo medio-lungo. L'itinerario alterna boschi, sentieri di crinale e tratti agricoli, offrendo una lettura completa del paesaggio toscano pre-fiorentino. L'impegno e di livello medio: non ci sono passaggi tecnici, ma servono passo costante e buona gestione dell'energia per affrontare i rilanci altimetrici. Il fondo e vario, spesso su sterrato e carrarecce, con possibile fango in caso di pioggia. Tappa adatta a chi ha gia ritmo da cammino di piu giorni e vuole mantenere continuita prima dell'arrivo a Firenze. Bastoncini consigliati per alleggerire le fasi di salita e discesa.",
  "3eedf593-5c51-4c95-b223-ebff4107696e":
    "Ultima tappa verso Firenze, generalmente piu favorevole altimetricamente ma comunque da gestire con attenzione per distanza e tratti di discesa. Il percorso accompagna gradualmente dall'ambiente collinare ai margini urbani, con passaggio progressivo da sentieri naturali a zone piu antropizzate. L'impegno e medio: meno salita rispetto alle tappe centrali, ma la stanchezza accumulata dei giorni precedenti puo farsi sentire. Fondo misto su sterrato, sentiero e brevi tratti asfaltati. E la giornata giusta per mantenere ritmo regolare, evitare partenze troppo aggressive e godersi la chiusura del cammino. Ottima tappa finale per chi cerca un arrivo appagante senza rinunciare alla componente escursionistica.",
};

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

try {
  const updates = Object.entries(descriptionsById);
  for (const [id, description] of updates) {
    await pool.query("UPDATE trails SET description = $2 WHERE id = $1", [id, description]);
  }
  const check = await pool.query(
    "SELECT id, name, char_length(description) AS len FROM trails WHERE id = ANY($1::uuid[]) ORDER BY name ASC",
    [Object.keys(descriptionsById)]
  );
  console.log(JSON.stringify(check.rows, null, 2));
} finally {
  await pool.end();
}
